// The catalogue. To add an asset: write src/assets/<id>.js exporting build() → THREE.Object3D,
// add an entry here, then run `node tools/thumbs.mjs <id>` to render its thumbnail.
//
// pose: rotZ tilts the model in its own plane, rotY turns it on the turntable (radians);
//       lift floats it above the floor (scene units, 1 = 10 cm).
// view: camera azimuth / elevation (radians) for the opening shot.

export const CATEGORIES = [
  { id: 'medical', name: 'Medical' },
  { id: 'weapons', name: 'Weapons' },
  { id: 'gear', name: 'Gear' },
  { id: 'tools', name: 'Tools' },
  { id: 'contraband', name: 'Contraband' },
];

export const ASSETS = [
  {
    id: 'medkit-bag', code: 'MED-001', name: 'White medkit bag', category: 'medical', added: '2026-10-07',
    pose: { rotY: .38 }, view: { az: .55, el: .32 },
    summary: 'Soft-sided first-aid pouch in white cordura with red trim.',
    features: [
      'Embroidered red cross on the lid and “FIRST AID” on the front',
      'Two-way #8 zipper around three sides, metal sliders with paracord pulls',
      'Bias-bound red piping and top-stitched panels',
      'Webbing carry handle with box-X stitched tabs',
      'Steel D-rings on both ends',
      'Clear PVC ID window with a filled-in card on the back',
    ],
  },
  {
    id: 'bandage-set', code: 'MED-002', name: 'Bandage set', category: 'medical', added: '2026-10-07',
    pose: {}, view: { az: .45, el: .5 },
    summary: 'Five dressings laid out on the bench, from roll gauze to plasters.',
    features: [
      'Open-weave cotton gauze roll, partly unrolled, with the layer spiral visible on its ends',
      'Elastic crepe bandage with toothed butterfly clips',
      'Cloth surgical tape on a ribbed plastic core, end peeled up',
      'Sterile 10 × 10 cm gauze pad pouch with crimped paper seal',
      'Adhesive plasters: two open, one in its wrapper',
    ],
  },
  {
    id: 'medkit-backpack', code: 'MED-003', name: 'Medkit backpack', category: 'medical', added: '2026-10-07',
    pose: { rotY: -.32 }, view: { az: .6, el: .25 },
    summary: 'Large EMS trauma backpack in red ripstop on a ballistic-nylon base.',
    features: [
      'Two-way main zipper over the top and down both sides',
      'Front pocket with its own zipper and a merrowed cross patch',
      'Reflective band across the upper front',
      'MOLLE rows and compression straps with side-release buckles',
      'Airmesh back pads and padded harness with sternum strap and ladder locks',
      'Padded top grab handle and hang loop',
    ],
  },
  {
    id: 'blood-bag', code: 'MED-004', name: 'Blood bag', category: 'medical', added: '2026-10-07',
    pose: { rotY: .2 }, view: { az: .35, el: .62 },
    summary: 'Unit of red blood cells in a clear PVC bag, lying flat with its donor tube coiled beside it.',
    features: [
      'Clear PVC pillow with an RF-welded frosted border, hanger holes and slit',
      'ISBT 128 style label: donation number, group O Rh positive, product code, expiry',
      'Printed volume scale in 50 mL steps',
      'Two outlet ports with twist-off protectors',
      'Donor tube filled with blood and heat-sealed into numbered segments',
    ],
  },
  {
    id: 'sword', code: 'WPN-001', name: 'Arming sword', category: 'weapons', added: '2026-10-07',
    pose: { rotZ: -.95, lift: .9 }, view: { az: .3, el: .18 },
    summary: 'Single-handed medieval sword with a fullered blade and wheel pommel.',
    features: [
      '80 cm lenticular blade with distal taper and a fuller over the first 60 %',
      'Brushed steel with honed, brighter edges',
      'Curved crossguard with flared terminals, central block and langets',
      'Leather-wrapped oval grip over two risers, steel ferrules',
      'Wheel pommel with peen block',
    ],
  },
  {
    id: 'machete', code: 'WPN-002', name: 'Machete', category: 'weapons', added: '2026-10-07',
    pose: { rotZ: -.95, lift: .7 }, view: { az: .3, el: .2 },
    summary: 'Latin-pattern field machete with a coated carbon-steel blade.',
    features: [
      '46 cm 1075 carbon-steel blade with a widening belly and upswept tip',
      'Black protective coating with scuffs, bright hand-ground edge bevel',
      'Moulded polymer handle with stippled grip, guard flare and hooked butt',
      'Brass rivets, brass lanyard grommet and an orange paracord loop',
    ],
  },
{
    id: 'pill', code: 'MED-005', name: 'Capsule pill', category: 'medical', added: '2026-10-08',
    pose: { rotY: .35 }, view: { az: .4, el: .35 },
    summary: 'A single two-tone hard gelatin capsule, shown big.',
    features: [
      'Size 0 capsule: 21.7 mm long, 7.3 mm wide',
      'Teal cap telescoped over a faintly translucent ivory body',
      'Sealing band and rounded rims where the halves meet',
      'Glossy gelatin finish with “LV 500” printed in edible ink',
      'Powder fill visible through the body',
    ],
  },
  {
    id: 'night-vision', code: 'GER-001', name: 'Night vision goggles', category: 'gear', added: '2026-10-08',
    pose: { rotY: -.55, lift: .3 }, view: { az: .45, el: .25 },
    summary: 'Dual-tube night vision binocular with articulating monoculars, switched on.',
    features: [
      'Two monoculars on articulating arms around a centre bridge',
      'Knurled objective and eyepiece focus rings with grip ribs',
      'Curved front glass over iridescent coated lens elements',
      'Rubber eyecups with green phosphor glow inside',
      'Dovetail mount shoe, rotary switch, IR illuminator, rear battery cap',
      'Printed model and serial markings',
    ],
  },
  {
    id: 'glasses', code: 'GER-002', name: 'Eyeglasses', category: 'gear', added: '2026-10-08',
    pose: { rotY: .5 }, view: { az: .55, el: .22 },
    summary: 'Tortoiseshell acetate glasses, size 52□20-145, temples open.',
    features: [
      'Polished tortoiseshell acetate front with a gentle face-wrap curve',
      'Anti-reflective lenses with a curved front surface',
      'Keyhole bridge and integrated nose pads',
      'Five-barrel metal hinges and decorative pin rivets',
      'Temples that bend down behind the ear, size printed inside',
    ],
  },
  {
    id: 'weed-bag', code: 'CTB-001', name: 'Bag of weed', category: 'contraband', added: '2026-10-08',
    pose: { rotY: .25 }, view: { az: .3, el: .7 },
    summary: 'Zip-seal baggie holding four cannabis buds and some shake.',
    features: [
      'Four buds built from lumpy colas, packed calyxes and sugar leaves',
      'Curly orange pistils and frosty trichomes over every bud',
      'Crinkled clear film with welded side seals',
      'Red zip track and lip at the top',
      'Write-on panel marked “3.5 g, OG Kush”',
    ],
  },
  {
    id: 'hammer', code: 'TOL-001', name: 'Claw hammer', category: 'tools', added: '2026-10-08',
    pose: { rotY: 0.4 }, view: { az: 0.4, el: 0.75 },
    summary: '16 oz claw hammer with a fibreglass shaft and rubber grip.',
    features: [
      'Forged head with a polished, slightly domed striking face',
      'Split nail claw with a V-slot between the prongs',
      'Fibreglass shaft with rubber over-moulded grip, yellow inlay and flared butt',
      '“16 OZ / 450 g” stamped on the cheek',
    ],
  },
  {
    id: 'flashlight', code: 'TOL-002', name: 'Flashlight', category: 'tools', added: '2026-10-08',
    pose: { rotY: 0.5 }, view: { az: 0.45, el: 0.45 },
    summary: 'Tactical LED flashlight in black anodised aluminium.',
    features: [
      'Knurled body tube and ribbed tail cap with a rubber switch boot',
      'Finned head, smooth reflector, LED emitter and glass lens',
      'Crenellated strike bezel',
      'Spring-steel pocket clip',
      '“800 lm · IPX8” printed on the head',
    ],
  },
  {
    id: 'screwdriver', code: 'TOL-003', name: 'Screwdriver', category: 'tools', added: '2026-10-08',
    pose: { rotY: 0.4 }, view: { az: 0.4, el: 0.5 },
    summary: 'PH2 × 125 mm Phillips screwdriver with a two-component handle.',
    features: [
      'Six-flute handle: hard red plastic with a soft black grip zone',
      'Hang hole through the end cap',
      'Hex bolster and chrome-vanadium shaft',
      'Black-oxide Phillips tip with four flutes',
    ],
  },
  {
    id: 'adjustable-wrench', code: 'TOL-004', name: 'Adjustable wrench', category: 'tools', added: '2026-10-08',
    pose: { rotY: 0.3 }, view: { az: 0.35, el: 0.7 },
    summary: '250 mm (10") chrome adjustable wrench.',
    features: [
      'Drop-forged chrome-vanadium body with hang hole',
      'Fixed jaw, sliding jaw and threaded worm in its window',
      'Size and jaw-scale markings',
    ],
  },
  {
    id: 'pliers', code: 'TOL-005', name: 'Combination pliers', category: 'tools', added: '2026-10-08',
    pose: { rotY: 0.3 }, view: { az: 0.35, el: 0.7 },
    summary: '200 mm combination pliers with dipped insulated grips.',
    features: [
      'Two forged halves crossing at a domed pivot rivet',
      'Serrated gripping jaws',
      'Dipped two-colour grips with flared ends',
      '“200 mm · 1000 V” marking',
    ],
  },
  {
    id: 'utility-knife', code: 'TOL-006', name: 'Utility knife', category: 'tools', added: '2026-10-08',
    pose: { rotY: 0.4 }, view: { az: 0.4, el: 0.7 },
    summary: '18 mm snap-off utility knife.',
    features: [
      'Yellow body with black rubber over-mould',
      'Chrome nose and segmented snap-off blade with score lines',
      'Ribbed slider, body screws and print',
    ],
  },
  {
    id: 'tape-measure', code: 'TOL-007', name: 'Tape measure', category: 'tools', added: '2026-10-08',
    pose: { rotY: -0.5 }, view: { az: 0.5, el: 0.3 },
    summary: '7.5 m / 25 ft tape measure with the blade pulled out.',
    features: [
      'Yellow case with a rubber bumper and side badge',
      'Lock button and chrome belt clip',
      'Cupped steel blade printed with mm/cm and inch scales',
      'Riveted end hook',
    ],
  },
  {
    id: 'hand-saw', code: 'TOL-008', name: 'Hand saw', category: 'tools', added: '2026-10-08',
    pose: { rotY: 0.3 }, view: { az: 0.3, el: 0.75 },
    summary: '550 mm (22") panel saw with a beech handle.',
    features: [
      'Tapered spring-steel blade with 7 TPI teeth, alternately set',
      'Etched maker’s mark and specs',
      'Closed beech handle with a hand hole',
      'Brass split-nut screws',
    ],
  },
  {
    id: 'spirit-level', code: 'TOL-009', name: 'Spirit level', category: 'tools', added: '2026-10-08',
    pose: { rotY: 0.35 }, view: { az: 0.35, el: 0.3 },
    summary: '600 mm spirit level with level and plumb vials.',
    features: [
      'Painted aluminium box section with milled reading edges',
      'Rubber end caps and hang hole',
      'Level and plumb vials with green fluid, bubbles and gauge rings',
      'Millimetre scale and maker’s label',
    ],
  },
  {
    id: 'crowbar', code: 'TOL-010', name: 'Crowbar', category: 'tools', added: '2026-10-08',
    pose: { rotY: 0.3 }, view: { az: 0.35, el: 0.75 },
    summary: '600 mm hexagonal wrecking bar.',
    features: [
      'Hex forged steel with a gooseneck nail claw',
      'Angled chisel end',
      'Red paint worn back to bare steel at both working ends',
    ],
  },
  {
    id: 'ratchet', code: 'TOL-011', name: 'Ratchet and socket', category: 'tools', added: '2026-10-08',
    pose: { rotY: -0.5 }, view: { az: 0.45, el: 0.35 },
    summary: '3/8" drive ratchet with a 13 mm socket.',
    features: [
      'Polished chrome handle with a rubber grip',
      'Round 72-tooth head with reversing lever and quick-release button',
      'Knurled 13 mm socket with size stamp',
    ],
  },
  {
    id: 'cordless-drill', code: 'TOL-012', name: 'Cordless drill', category: 'tools', added: '2026-10-08',
    pose: { rotY: -0.45 }, view: { az: 0.5, el: 0.22 },
    summary: '18 V cordless drill/driver standing on its battery.',
    features: [
      'Teal and black housing with rear vents and 2-speed selector',
      'Numbered clutch collar, keyless chuck and bit',
      'Rubber-gripped handle, trigger and direction switch',
      'Work light and battery pack with a charge gauge',
    ],
  },
  {
    id: 'tactical-backpack', code: 'GER-003', name: 'Tactical backpack', category: 'gear', added: '2026-10-08',
    pose: { rotY: -0.35 }, view: { az: 0.55, el: 0.25 },
    summary: '3-day assault pack in coyote brown cordura, covered in PALS webbing.',
    features: [
      'Full-width PALS/MOLLE grid on the front and both sides, bar-tacked every 1.5"',
      'Zippered admin pocket with hook-and-loop field and a raised PVC morale patch',
      'Two-way main zipper with paracord pulls; binding tape on all seams',
      'Side compression straps with side-release buckles',
      'Drag handle with box-X stitching and a hydration port',
      'Airmesh back pads, padded harness with PALS loops, sternum strap and ladder-lock adjusters',
    ],
  },
  {
    id: 'pistol', code: 'WPN-003', name: 'Pistol', category: 'weapons', added: '2026-10-08',
    pose: { rotY: 0.15, lift: 0.3 }, view: { az: 0.3, el: 0.15 },
    summary: 'Compact 9 mm striker-fired pistol with a threaded barrel.',
    features: [
      'Polymer frame: stippled grip panels, finger grooves, undercut trigger guard, accessory rail',
      'Nitrided slide with front and rear serrations',
      'Ejection port showing the stainless barrel hood',
      'Three-dot sights with a tritium front insert',
      'Trigger safety blade, slide stop, takedown lever, magazine release',
      'Threaded barrel protruding for a suppressor',
    ],
  },
  {
    id: 'revolver', code: 'WPN-004', name: 'Revolver', category: 'weapons', added: '2026-10-08',
    pose: { rotY: 0.15, lift: 0.3 }, view: { az: 0.3, el: 0.15 },
    summary: '.357 Magnum double-action revolver with a 4" barrel, loaded.',
    features: [
      'Satin stainless frame with top strap and screwed side plate',
      'Six-shot fluted cylinder with copper-jacketed rounds in every chamber',
      'Full-underlug barrel with a ventilated top rib and red-insert ramp sight',
      'Adjustable rear sight, checkered hammer spur, smooth combat trigger, cylinder release',
      'Checkered walnut grips with steel medallions',
      'Roll-marked caliber and model',
    ],
  },
  {
    id: 'ak-rifle', code: 'WPN-005', name: 'AK-pattern rifle', category: 'weapons', added: '2026-10-08',
    pose: { rotY: 0.12, lift: 0.3 }, view: { az: 0.3, el: 0.12 },
    summary: 'AKM-pattern 7.62×39 mm rifle with laminated wood furniture.',
    features: [
      'Stamped receiver with ribbed dust cover, rivets, selector lever and charging handle',
      'Tangent rear sight graduated 1–10',
      'Curved 30-round steel magazine with stamped ribs',
      'Bakelite pistol grip; laminated stock, handguards and steel buttplate',
      'Gas tube and block, hooded front sight, bayonet lug and cleaning rod',
      'Slant muzzle brake',
    ],
  },
  {
    id: 'shotgun', code: 'WPN-006', name: 'Pump shotgun', category: 'weapons', added: '2026-10-08',
    pose: { rotY: 0.12, lift: 0.3 }, view: { az: 0.3, el: 0.12 },
    summary: '12-gauge pump-action shotgun with a 20" vent-rib barrel and walnut furniture.',
    features: [
      'Blued receiver with ejection port, chrome bolt and loading port',
      'Vent-rib barrel with a brass bead',
      'Magazine tube with knurled cap and barrel clamp',
      'Ribbed walnut forend on twin action bars',
      'Cross-bolt safety and slide release',
      'Checkered walnut stock, rubber recoil pad with white-line spacer, sling swivels',
    ],
  },
  {
    id: 'sniper-rifle', code: 'WPN-007', name: 'Sniper rifle', category: 'weapons', added: '2026-10-08',
    pose: { rotY: 0.15, lift: 0.2 }, view: { az: 0.4, el: 0.18 },
    summary: '.308 bolt-action precision rifle with a 5–25×56 scope and bipod.',
    features: [
      'Round action with tactical bolt knob and Picatinny rail',
      'Fluted heavy barrel and ported muzzle brake',
      'Stippled flat-dark-earth stock with vertical grip, adjustable cheek riser and recoil pad',
      'Riflescope: elevation, windage and side-focus turrets, illumination dial, throw lever, sunshade, coated lenses',
      'Two scope rings with cross-bolts',
      'Deployed bipod with extendable legs and rubber feet',
    ],
  },
  {
    id: 'suppressor', code: 'WPN-008', name: 'Suppressor', category: 'weapons', added: '2026-10-08',
    pose: { rotY: 0.0, lift: 0.4 }, view: { az: 0.5, el: 0.35 },
    summary: '9 mm pistol suppressor shown with a quarter cut away to reveal the baffles.',
    features: [
      '1.5" × 7.3" black Cerakote titanium tube',
      'Knurled rear mount with internal 1/2-28 threads',
      'Blast chamber and a stack of nine cone baffles with spacer skirts',
      'Front cap with wrench notches',
      'Bare machined metal on the cut faces',
      'Laser-etched model and serial markings',
    ],
  },
];
