// The catalogue. To add an asset: write src/assets/<id>.js exporting build() → THREE.Object3D,
// add an entry here, then run `node tools/thumbs.mjs <id>` to render its thumbnail.
//
// pose: rotZ tilts the model in its own plane, rotY turns it on the turntable (radians);
//       lift floats it above the floor (scene units, 1 = 10 cm).
// view: camera azimuth / elevation (radians) for the opening shot.

export const CATEGORIES = [
  { id: 'medical', name: 'Medical' },
  { id: 'weapons', name: 'Weapons' },
  { id: 'gear', name: 'Gear' },
  { id: 'tools', name: 'Tools' },
  { id: 'contraband', name: 'Contraband' },
  { id: 'food', name: 'Food' },
];

export const ASSETS = [
  {
    id: 'medkit-bag', code: 'MED-001', name: 'White medkit bag', category: 'medical', added: '2026-10-07',
    pose: { rotY: .38 }, view: { az: .55, el: .32 },
    summary: 'Soft-sided first-aid pouch in white cordura with red trim.',
    features: [
      'Embroidered red cross on the lid and “FIRST AID” on the front',
      'Two-way #8 zipper around three sides, metal sliders with paracord pulls',
      'Bias-bound red piping and top-stitched panels',
      'Webbing carry handle with box-X stitched tabs',
      'Steel D-rings on both ends',
      'Clear PVC ID window with a filled-in card on the back',
    ],
  },
  {
    id: 'bandage-set', code: 'MED-002', name: 'Bandage set', category: 'medical', added: '2026-10-07',
    pose: {}, view: { az: .45, el: .5 },
    summary: 'Five dressings laid out on the bench, from roll gauze to plasters.',
    features: [
      'Open-weave cotton gauze roll, partly unrolled, with the layer spiral visible on its ends',
      'Elastic crepe bandage with toothed butterfly clips',
      'Cloth surgical tape on a ribbed plastic core, end peeled up',
      'Sterile 10 × 10 cm gauze pad pouch with crimped paper seal',
      'Adhesive plasters: two open, one in its wrapper',
    ],
  },
  {
    id: 'medkit-backpack', code: 'MED-003', name: 'Medkit backpack', category: 'medical', added: '2026-10-07',
    pose: { rotY: -.32 }, view: { az: .6, el: .25 },
    summary: 'Large EMS trauma backpack in red ripstop on a ballistic-nylon base.',
    features: [
      'Two-way main zipper over the top and down both sides',
      'Front pocket with its own zipper and a merrowed cross patch',
      'Reflective band across the upper front',
      'MOLLE rows and compression straps with side-release buckles',
      'Airmesh back pads and padded harness with sternum strap and ladder locks',
      'Padded top grab handle and hang loop',
    ],
  },
  {
    id: 'blood-bag', code: 'MED-004', name: 'Blood bag', category: 'medical', added: '2026-10-07',
    pose: { rotY: .2 }, view: { az: .35, el: .62 },
    summary: 'Unit of red blood cells in a clear PVC bag, lying flat with its donor tube coiled beside it.',
    features: [
      'Clear PVC pillow with an RF-welded frosted border, hanger holes and slit',
      'ISBT 128 style label: donation number, group O Rh positive, product code, expiry',
      'Printed volume scale in 50 mL steps',
      'Two outlet ports with twist-off protectors',
      'Donor tube filled with blood and heat-sealed into numbered segments',
    ],
  },
  {
    id: 'sword', code: 'WPN-001', name: 'Arming sword', category: 'weapons', added: '2026-10-07',
    pose: { rotZ: -.95, lift: .9 }, view: { az: .3, el: .18 },
    summary: 'Single-handed medieval sword with a fullered blade and wheel pommel.',
    features: [
      '80 cm lenticular blade with distal taper and a fuller over the first 60 %',
      'Brushed steel with honed, brighter edges',
      'Curved crossguard with flared terminals, central block and langets',
      'Leather-wrapped oval grip over two risers, steel ferrules',
      'Wheel pommel with peen block',
    ],
  },
  {
    id: 'machete', code: 'WPN-002', name: 'Machete', category: 'weapons', added: '2026-10-07',
    pose: { rotZ: -.95, lift: .7 }, view: { az: .3, el: .2 },
    summary: 'Latin-pattern field machete with a coated carbon-steel blade.',
    features: [
      '46 cm 1075 carbon-steel blade with a widening belly and upswept tip',
      'Black protective coating with scuffs, bright hand-ground edge bevel',
      'Moulded polymer handle with stippled grip, guard flare and hooked butt',
      'Brass rivets, brass lanyard grommet and an orange paracord loop',
    ],
  },
{
    id: 'pill', code: 'MED-005', name: 'Capsule pill', category: 'medical', added: '2026-10-08',
    pose: { rotY: .35 }, view: { az: .4, el: .35 },
    summary: 'A single two-tone hard gelatin capsule, shown big.',
    features: [
      'Size 0 capsule: 21.7 mm long, 7.3 mm wide',
      'Teal cap telescoped over a faintly translucent ivory body',
      'Sealing band and rounded rims where the halves meet',
      'Glossy gelatin finish with “LV 500” printed in edible ink',
      'Powder fill visible through the body',
    ],
  },
  {
    id: 'night-vision', code: 'GER-001', name: 'Night vision goggles', category: 'gear', added: '2026-10-08',
    pose: { rotY: -.55, lift: .3 }, view: { az: .45, el: .25 },
    summary: 'Dual-tube night vision binocular with articulating monoculars, switched on.',
    features: [
      'Two monoculars on articulating arms around a centre bridge',
      'Knurled objective and eyepiece focus rings with grip ribs',
      'Curved front glass over iridescent coated lens elements',
      'Rubber eyecups with green phosphor glow inside',
      'Dovetail mount shoe, rotary switch, IR illuminator, rear battery cap',
      'Printed model and serial markings',
    ],
  },
  {
    id: 'glasses', code: 'GER-002', name: 'Eyeglasses', category: 'gear', added: '2026-10-08',
    pose: { rotY: .5 }, view: { az: .55, el: .22 },
    summary: 'Tortoiseshell acetate glasses, size 52□20-145, temples open.',
    features: [
      'Polished tortoiseshell acetate front with a gentle face-wrap curve',
      'Anti-reflective lenses with a curved front surface',
      'Keyhole bridge and integrated nose pads',
      'Five-barrel metal hinges and decorative pin rivets',
      'Temples that bend down behind the ear, size printed inside',
    ],
  },
  {
    id: 'weed-bag', code: 'CTB-001', name: 'Bag of weed', category: 'contraband', added: '2026-10-08',
    pose: { rotY: .25 }, view: { az: .3, el: .7 },
    summary: 'Zip-seal baggie holding four cannabis buds and some shake.',
    features: [
      'Four buds built from lumpy colas, packed calyxes and sugar leaves',
      'Curly orange pistils and frosty trichomes over every bud',
      'Crinkled clear film with welded side seals',
      'Red zip track and lip at the top',
      'Write-on panel marked “3.5 g, OG Kush”',
    ],
  },
  {
    id: 'hammer', code: 'TOL-001', name: 'Claw hammer', category: 'tools', added: '2026-10-08',
    pose: { rotY: 0.4 }, view: { az: 0.4, el: 0.75 },
    summary: '16 oz claw hammer with a fibreglass shaft and rubber grip.',
    features: [
      'Forged head with a polished, slightly domed striking face',
      'Split nail claw with a V-slot between the prongs',
      'Fibreglass shaft with rubber over-moulded grip, yellow inlay and flared butt',
      '“16 OZ / 450 g” stamped on the cheek',
    ],
  },
  {
    id: 'flashlight', code: 'TOL-002', name: 'Flashlight', category: 'tools', added: '2026-10-08',
    pose: { rotY: 0.5 }, view: { az: 0.45, el: 0.45 },
    summary: 'Tactical LED flashlight in black anodised aluminium.',
    features: [
      'Knurled body tube and ribbed tail cap with a rubber switch boot',
      'Finned head, smooth reflector, LED emitter and glass lens',
      'Crenellated strike bezel',
      'Spring-steel pocket clip',
      '“800 lm · IPX8” printed on the head',
    ],
  },
  {
    id: 'screwdriver', code: 'TOL-003', name: 'Screwdriver', category: 'tools', added: '2026-10-08',
    pose: { rotY: 0.4 }, view: { az: 0.4, el: 0.5 },
    summary: 'PH2 × 125 mm Phillips screwdriver with a two-component handle.',
    features: [
      'Six-flute handle: hard red plastic with a soft black grip zone',
      'Hang hole through the end cap',
      'Hex bolster and chrome-vanadium shaft',
      'Black-oxide Phillips tip with four flutes',
    ],
  },
  {
    id: 'adjustable-wrench', code: 'TOL-004', name: 'Adjustable wrench', category: 'tools', added: '2026-10-08',
    pose: { rotY: 0.3 }, view: { az: 0.35, el: 0.7 },
    summary: '250 mm (10") chrome adjustable wrench.',
    features: [
      'Drop-forged chrome-vanadium body with hang hole',
      'Fixed jaw, sliding jaw and threaded worm in its window',
      'Size and jaw-scale markings',
    ],
  },
  {
    id: 'pliers', code: 'TOL-005', name: 'Combination pliers', category: 'tools', added: '2026-10-08',
    pose: { rotY: 0.3 }, view: { az: 0.35, el: 0.7 },
    summary: '200 mm combination pliers with dipped insulated grips.',
    features: [
      'Two forged halves crossing at a domed pivot rivet',
      'Serrated gripping jaws',
      'Dipped two-colour grips with flared ends',
      '“200 mm · 1000 V” marking',
    ],
  },
  {
    id: 'utility-knife', code: 'TOL-006', name: 'Utility knife', category: 'tools', added: '2026-10-08',
    pose: { rotY: 0.4 }, view: { az: 0.4, el: 0.7 },
    summary: '18 mm snap-off utility knife.',
    features: [
      'Yellow body with black rubber over-mould',
      'Chrome nose and segmented snap-off blade with score lines',
      'Ribbed slider, body screws and print',
    ],
  },
  {
    id: 'tape-measure', code: 'TOL-007', name: 'Tape measure', category: 'tools', added: '2026-10-08',
    pose: { rotY: -0.5 }, view: { az: 0.5, el: 0.3 },
    summary: '7.5 m / 25 ft tape measure with the blade pulled out.',
    features: [
      'Yellow case with a rubber bumper and side badge',
      'Lock button and chrome belt clip',
      'Cupped steel blade printed with mm/cm and inch scales',
      'Riveted end hook',
    ],
  },
  {
    id: 'hand-saw', code: 'TOL-008', name: 'Hand saw', category: 'tools', added: '2026-10-08',
    pose: { rotY: 0.3 }, view: { az: 0.3, el: 0.75 },
    summary: '550 mm (22") panel saw with a beech handle.',
    features: [
      'Tapered spring-steel blade with 7 TPI teeth, alternately set',
      'Etched maker’s mark and specs',
      'Closed beech handle with a hand hole',
      'Brass split-nut screws',
    ],
  },
  {
    id: 'spirit-level', code: 'TOL-009', name: 'Spirit level', category: 'tools', added: '2026-10-08',
    pose: { rotY: 0.35 }, view: { az: 0.35, el: 0.3 },
    summary: '600 mm spirit level with level and plumb vials.',
    features: [
      'Painted aluminium box section with milled reading edges',
      'Rubber end caps and hang hole',
      'Level and plumb vials with green fluid, bubbles and gauge rings',
      'Millimetre scale and maker’s label',
    ],
  },
  {
    id: 'crowbar', code: 'TOL-010', name: 'Crowbar', category: 'tools', added: '2026-10-08',
    pose: { rotY: 0.3 }, view: { az: 0.35, el: 0.75 },
    summary: '600 mm hexagonal wrecking bar.',
    features: [
      'Hex forged steel with a gooseneck nail claw',
      'Angled chisel end',
      'Red paint worn back to bare steel at both working ends',
    ],
  },
  {
    id: 'ratchet', code: 'TOL-011', name: 'Ratchet and socket', category: 'tools', added: '2026-10-08',
    pose: { rotY: -0.5 }, view: { az: 0.45, el: 0.35 },
    summary: '3/8" drive ratchet with a 13 mm socket.',
    features: [
      'Polished chrome handle with a rubber grip',
      'Round 72-tooth head with reversing lever and quick-release button',
      'Knurled 13 mm socket with size stamp',
    ],
  },
  {
    id: 'cordless-drill', code: 'TOL-012', name: 'Cordless drill', category: 'tools', added: '2026-10-08',
    pose: { rotY: -0.45 }, view: { az: 0.5, el: 0.22 },
    summary: '18 V cordless drill/driver standing on its battery.',
    features: [
      'Teal and black housing with rear vents and 2-speed selector',
      'Numbered clutch collar, keyless chuck and bit',
      'Rubber-gripped handle, trigger and direction switch',
      'Work light and battery pack with a charge gauge',
    ],
  },
  {
    id: 'tactical-backpack', code: 'GER-003', name: 'Tactical backpack', category: 'gear', added: '2026-10-08',
    pose: { rotY: -0.35 }, view: { az: 0.55, el: 0.25 },
    summary: '3-day assault pack in coyote brown cordura, covered in PALS webbing.',
    features: [
      'Full-width PALS/MOLLE grid on the front and both sides, bar-tacked every 1.5"',
      'Zippered admin pocket with hook-and-loop field and a raised PVC morale patch',
      'Two-way main zipper with paracord pulls; binding tape on all seams',
      'Side compression straps with side-release buckles',
      'Drag handle with box-X stitching and a hydration port',
      'Airmesh back pads, padded harness with PALS loops, sternum strap and ladder-lock adjusters',
    ],
  },
  {
    id: 'pistol', code: 'WPN-003', name: 'Pistol', category: 'weapons', added: '2026-10-08',
    pose: { rotY: 0.15, lift: 0.3 }, view: { az: 0.3, el: 0.15 },
    summary: 'Compact 9 mm striker-fired pistol with a threaded barrel.',
    features: [
      'Polymer frame: stippled grip panels, finger grooves, undercut trigger guard, accessory rail',
      'Nitrided slide with front and rear serrations',
      'Ejection port showing the stainless barrel hood',
      'Three-dot sights with a tritium front insert',
      'Trigger safety blade, slide stop, takedown lever, magazine release',
      'Threaded barrel protruding for a suppressor',
    ],
  },
  {
    id: 'revolver', code: 'WPN-004', name: 'Revolver', category: 'weapons', added: '2026-10-08',
    pose: { rotY: 0.15, lift: 0.3 }, view: { az: 0.3, el: 0.15 },
    summary: '.357 Magnum double-action revolver with a 4" barrel, loaded.',
    features: [
      'Satin stainless frame with top strap and screwed side plate',
      'Six-shot fluted cylinder with copper-jacketed rounds in every chamber',
      'Full-underlug barrel with a ventilated top rib and red-insert ramp sight',
      'Adjustable rear sight, checkered hammer spur, smooth combat trigger, cylinder release',
      'Checkered walnut grips with steel medallions',
      'Roll-marked caliber and model',
    ],
  },
  {
    id: 'ak-rifle', code: 'WPN-005', name: 'AK-pattern rifle', category: 'weapons', added: '2026-10-08',
    pose: { rotY: 0.12, lift: 0.3 }, view: { az: 0.3, el: 0.12 },
    summary: 'AKM-pattern 7.62×39 mm rifle with laminated wood furniture.',
    features: [
      'Stamped receiver with ribbed dust cover, rivets, selector lever and charging handle',
      'Tangent rear sight graduated 1–10',
      'Curved 30-round steel magazine with stamped ribs',
      'Bakelite pistol grip; laminated stock, handguards and steel buttplate',
      'Gas tube and block, hooded front sight, bayonet lug and cleaning rod',
      'Slant muzzle brake',
    ],
  },
  {
    id: 'shotgun', code: 'WPN-006', name: 'Pump shotgun', category: 'weapons', added: '2026-10-08',
    pose: { rotY: 0.12, lift: 0.3 }, view: { az: 0.3, el: 0.12 },
    summary: '12-gauge pump-action shotgun with a 20" vent-rib barrel and walnut furniture.',
    features: [
      'Blued receiver with ejection port, chrome bolt and loading port',
      'Vent-rib barrel with a brass bead',
      'Magazine tube with knurled cap and barrel clamp',
      'Ribbed walnut forend on twin action bars',
      'Cross-bolt safety and slide release',
      'Checkered walnut stock, rubber recoil pad with white-line spacer, sling swivels',
    ],
  },
  {
    id: 'sniper-rifle', code: 'WPN-007', name: 'Sniper rifle', category: 'weapons', added: '2026-10-08',
    pose: { rotY: 0.15, lift: 0.2 }, view: { az: 0.4, el: 0.18 },
    summary: '.308 bolt-action precision rifle with a 5–25×56 scope and bipod.',
    features: [
      'Round action with tactical bolt knob and Picatinny rail',
      'Fluted heavy barrel and ported muzzle brake',
      'Stippled flat-dark-earth stock with vertical grip, adjustable cheek riser and recoil pad',
      'Riflescope: elevation, windage and side-focus turrets, illumination dial, throw lever, sunshade, coated lenses',
      'Two scope rings with cross-bolts',
      'Deployed bipod with extendable legs and rubber feet',
    ],
  },
  {
    id: 'suppressor', code: 'WPN-008', name: 'Suppressor', category: 'weapons', added: '2026-10-08',
    pose: { rotY: 0.0, lift: 0.4 }, view: { az: 0.5, el: 0.35 },
    summary: '9 mm pistol suppressor shown with a quarter cut away to reveal the baffles.',
    features: [
      '1.5" × 7.3" black Cerakote titanium tube',
      'Knurled rear mount with internal 1/2-28 threads',
      'Blast chamber and a stack of nine cone baffles with spacer skirts',
      'Front cap with wrench notches',
      'Bare machined metal on the cut faces',
      'Laser-etched model and serial markings',
    ],
  },
  {
    id: 'm16', code: 'WPN-009', name: 'M16A2 rifle', category: 'weapons', added: '2026-10-08',
    pose: { rotY: 0, lift: .3 }, view: { az: .25, el: .12 },
    summary: 'M16A2 service rifle, 1006 mm, modelled from traced reference photographs.',
    features: [
      'Silhouette and proportions traced from a reference photograph at true scale (1006 mm overall, 20" barrel)',
      'Anodised upper and lower receivers, parkerised barrel and front sight base, black polymer furniture, grey aluminium magazine',
      'Carry handle with A2 rear sight: windage knob, elevation drum and flip aperture',
      'Forward assist, brass deflector, ejection port dust cover, charging handle',
      'Round A2 handguards with two bands of ribs, delta ring and handguard cap',
      'Selector marked SAFE / SEMI / BURST, bolt catch, magazine release with fence',
      'A2 front sight base with bayonet lug and swivel; birdcage flash hider closed at the bottom',
    ],
  },
  {
    id: 'k12', code: 'WPN-010', name: 'K-12 Sport pistol', category: 'weapons', added: '2026-10-08',
    pose: { rotY: 0, lift: .3 }, view: { az: .3, el: .12 },
    summary: 'Full-size 9 mm competition pistol, traced from a side photograph at its 216 mm length.',
    features: [
      'Silhouette traced from a reference photo at true scale (216 mm long, 4.7" barrel)',
      'Grey Cerakote steel frame with beavertail and squared trigger guard',
      'Slide riding low in the frame rails, slanted front and rear serrations',
      'Chrome barrel hood showing through the slide top, extractor, crowned muzzle',
      'Adjustable rear sight with windage and elevation screws, steel front post',
      'Extended safety, magazine release, skeleton hammer, black trigger',
      'Aluminium grip panels with a machined pocket, checkered front and back straps, stepped base pad',
    ],
  },
  {
    id: 'hellion', code: 'WPN-011', name: 'Hellion bullpup', category: 'weapons', added: '2026-10-09',
    pose: { rotY: 0, lift: .3 }, view: { az: .35, el: .15 },
    summary: 'Springfield Hellion-style 5.56 mm bullpup with a 1–8× optic, traced from a VHS-2 side photograph.',
    features: [
      'Silhouette traced from a side photograph at true scale (718 mm overall, 16" barrel)',
      'Polymer chassis with adjustable buttstock and rubber butt pad',
      'Top carry rail with integrated flip-up sights and a long side window',
      'Forward charging handle, ambidextrous selector, switchable ejection-port covers',
      'M-LOK slots and a lower accessory rail on the handguard',
      'PMAG-style magazine with waffle band; four-prong flash hider on a 16 in barrel',
      '1–8×24 LPVO with throw lever and capped turrets in a one-piece cantilever mount',
    ],
  },
  {
    id: 'revolver686', code: 'WPN-012', name: '686 stainless revolver', category: 'weapons', added: '2026-10-09',
    pose: { rotY: 0, lift: .3 }, view: { az: .3, el: .12 },
    summary: 'Stainless 4" .357 Magnum double-action revolver with a black rubber grip, traced from a photograph at its 243 mm length.',
    features: [
      'Silhouette traced from a reference photo at true scale (243 mm long, 4" barrel)',
      'Brushed stainless frame with top strap, cylinder window and sideplate screws',
      'Six-shot fluted cylinder with chambers, bolt cuts and centre pin',
      'Half-lug barrel with top rib, crowned muzzle and the ejector rod visible in its shroud',
      'Pinned ramp front sight with red insert, adjustable black rear sight',
      'Checkered hammer spur, smooth trigger, cylinder-release thumbpiece',
      'Black finger-groove rubber grip with stippled texture',
    ],
  },
  {
    id: 'ar-pistol', code: 'WPN-013', name: 'AR-15 pistol', category: 'weapons', added: '2026-10-09',
    pose: { rotY: 0, lift: .3 }, view: { az: .35, el: .15 },
    summary: 'Short-barrelled AR-15 pistol with a pistol brace, red dot on a riser, free-float rail and angled foregrip.',
    features: [
      'Lower receiver, grip and magazine share the outlines traced for the M16',
      '7.5" barrel with birdcage flash hider inside a free-float slotted rail',
      'Flat-top upper with Picatinny rail, ejection port cover, forward assist',
      'Troy-style pistol brace on a buffer tube with castle nut',
      'Holosun-style red dot with side buttons, solar panel and turrets on a riser',
      'Flip-up front and rear sights, bronze barrel nut, QD sling sockets',
      'Olive-drab angled foregrip, black PMAG with waffle band and flared floorplate',
    ],
  },
  {
    id: 'seeded-roll', code: 'FD-001', name: 'Seeded breakfast roll', category: 'food', added: '2026-10-09',
    pose: { rotY: 0, lift: 0 }, view: { az: .45, el: .4 },
    summary: 'Multigrain breakfast roll under a mixed seed crust, shown whole and cut in half.',
    features: [
      'Domed roll about 100 mm across and 58 mm tall with a flat, paler heel',
      'Baked colour gradient from golden sides to a deep brown crown, blistered crust bump',
      'Topping of sunflower and pumpkin kernels, sesame, brown and golden linseed, rolled oats',
      'Second roll cut in half showing open, seed-flecked crumb and a thin crust rim',
    ],
  },
  {
    id: 'oat-cookie-pack', code: 'FD-002', name: 'Oat cookie pack', category: 'food', added: '2026-10-09',
    pose: { rotY: 0, lift: 0 }, view: { az: .5, el: .35 },
    summary: 'Printed flow-wrap roll of 22 oat cookies, torn open with three cookies out on the table.',
    features: [
      'Glossy printed OPP tube, 70 mm across and 200 mm long, with a crimp-sealed fin and back seal',
      'Torn-open end with a ragged, flared film edge and a metallised inner face',
      'Front print: logo panel, title, oat-flake badge, cookie illustration; back: ingredients, nutrition, barcode',
      'Stack of 22 cookies inside, the next one in view at the open end',
      'Cookies about 62 mm by 9 mm: craggy domed tops, hairline cracks, oat flakes, sugar sparkle, darker edges',
      'Crumbs scattered on the table',
    ],
  },
  {
    id: 'bakery-sandwich', code: 'FD-003', name: 'Bakery lunch sandwich', category: 'food', added: '2026-10-09',
    pose: { rotY: 0, lift: 0 }, view: { az: .55, el: .35 },
    summary: 'Jambon-beurre on a half baguette tradition, split and filled, half in a kraft window bag.',
    features: [
      '280 mm half baguette with a flattened base, three grigne scores with raised ears and patchy flour',
      'Split low along the front and hinged at the back, top lifted to show the filling',
      'Open crumb on both cut faces, uneven butter smear',
      'Three ham slices folded in waves over the cut edge, two emmental slices with eyes',
      'Kraft sandwich bag with fibre texture, clear window, folded end and printed label',
    ],
  },
  {
    id: 'soup-flask', code: 'FD-004', name: 'Garden soup flask', category: 'food', added: '2026-10-09',
    pose: { rotY: 0, lift: 0 }, view: { az: .35, el: .45 },
    summary: 'Vacuum-insulated 470 ml stainless food jar, opened, full of garden vegetable soup with the folding spoon in it.',
    features: [
      'Food-jar profile: 98 mm base band, 94 mm body, two grip grooves around a raised belly band',
      'Black badge with a polished border on the belly band, dark neck seal, threaded neck',
      'Bead-blasted stainless with circumferential brushing; polished inner wall',
      'Screw lid (doubles as a bowl) and grey inner stopper with silicone seal set beside the jar',
      'Tomato-based soup with carrot dice, peas, courgette, celery, potato, herb flecks and oil droplets',
      'Folding stainless spoon, unfolded, resting in the soup',
    ],
  },
];
